Update upload_to_steam.yml

diff --git a/.github/workflows/upload_to_steam.yml b/.github/workflows/upload_to_steam.yml
--- a/.github/workflows/upload_to_steam.yml
+++ b/.github/workflows/upload_to_steam.yml
@@ -20,21 +20,44 @@ jobs:
         
       - name: Create VDF file
         run: |
-          cat <<EOF > workshop_upload.vdf
+          echo "Generating workshop-item.vdf"
+          cat <<EOF > workshop-item.vdf
           "workshopitem"
           {
               "appid"            "1201540"
               "publishedfileid"  "3538327453"
-              "contentfolder"    "ccg_mod/"
+              "contentfolder"    "\ccg_mod"
               "changenote"       "${{ github.event.head_commit.message }}"
           }
           EOF
-          
+          echo "Created workshop-item.vdf"
+
+      - name: Check steamcmd and config file
+        run: |
+          steamdir=${STEAM_HOME:-$HOME/Steam}
+          echo "Steam is installed in: $steamdir"
+          mkdir -p "$steamdir/config"
+          echo "$STEAM_VDF" > "$steamdir/config/config.vdf"
+          chmod 777 "$steamdir/config/config.vdf"
+          echo "Test Login"
+          steamcmd +login "$steam_username" +quit;
+          ret=$?
+          if [ $ret -eq 0 ]; then
+              echo "Successful login"
+          else
+                echo "FAILED login"
+                echo "Exit code: $ret"
+                exit $ret
+          fi
+        env:
+          STEAM_VDF: ${{ secrets.STEAM_VDF }}
+      
       - name: Upload mod to Steam Workshop
         run: |
-          steamcmd +login "$STEAM_USERNAME" "$STEAM_PASSWORD" \
+          steamcmd +login "$STEAM_USERNAME" \
                    +workshop_build_item "workshop_upload.vdf" \
                    +quit
         env:
           STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
           STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
+          
